# Generated by Django 2.2.4 on 2019-09-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atesttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='heattreatment',
            options={'managed': False, 'ordering': ['term']},
        ),
        migrations.AlterModelOptions(
            name='machiningtype',
            options={'managed': False, 'ordering': ['machining']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'managed': False, 'ordering': ['material']},
        ),
        migrations.AlterModelOptions(
            name='materialgroup',
            options={'managed': False, 'ordering': ['mat_group']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='offerpatternstatus',
            options={'managed': False, 'verbose_name_plural': 'Offer pattern statuses'},
        ),
        migrations.AlterModelOptions(
            name='offerstatus',
            options={'managed': False, 'ordering': ['-offer_status'], 'verbose_name_plural': 'Offer statuses'},
        ),
        migrations.AlterModelOptions(
            name='patterntaper',
            options={'managed': False},
        ),
    ]
